# Generated by Django 3.2.5 on 2021-07-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelement',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
