# Generated by Django 3.2.5 on 2021-07-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cartelement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartelement',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
