# Generated by Django 3.2.5 on 2021-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210719_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartelement',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
